package org.hidetake.blebutton

enum class BleState {
    INIT,
    CONNECTING,
    CONNECTED,
    SERVICE_DISCOVERED,
    SENDING_LINK_LOSS,
    SENT_LINK_LOSS,
    SENDING_BUTTON_DESCRIPTOR,
    SENT_BUTTON_DESCRIPTOR,
    IDLE,
    BUTTON_PRESSED,
    SENDING_ALARM_START,
    SENT_ALARM_START,
    SENDING_ALARM_STOP,
    SENT_ALARM_STOP,
    CLOSING,
    CLOSED,
}
